# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on: #Events/trigger
  push:
    branches: [ "main", "frontend-testing" ]
  pull_request:
    branches: [ "main", "frontend-testing" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest #runner container evn

    steps: #actions being done
    - name: Checkout code
      uses: actions/checkout@v3
    # ---------------------------
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    # ---------------------------
    - name: Run Super-Linter
      uses: github/super-linter@v3
    # # ---------------------------
    # - name: Install dependencies
    #   run: |
    #     python -m pip install --upgrade pip
    #     pip install flake8 pytest
    #     if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    # # ---------------------------
    # - name: Test with pytest
    #   run: |
    #     pytest
